"""phase1_core_scheduling

Revision ID: 1113f8542f00
Revises: ebf79c1d9b2d
Create Date: 2026-04-20 16:01:53.829106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1113f8542f00'
down_revision: Union[str, None] = 'ebf79c1d9b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_households',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_households_tenant_id'), 'client_households', ['tenant_id'], unique=False)
    op.create_table('departments',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('can_be_cashier', sa.Boolean(), nullable=False),
    sa.Column('makes_appointments', sa.Boolean(), nullable=False),
    sa.Column('has_appointments', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('service_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_categories_tenant_id'), 'service_categories', ['tenant_id'], unique=False)
    op.create_table('tenant_operating_hours',
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_operating_hours_tenant_id'), 'tenant_operating_hours', ['tenant_id'], unique=False)
    op.create_table('appointment_requests',
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('converted_to_appointment_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('pronouns', sa.String(length=50), nullable=True),
    sa.Column('submitted_by_name', sa.String(length=255), nullable=True),
    sa.Column('desired_date', sa.DateTime(), nullable=False),
    sa.Column('desired_time_note', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('online_form', 'email', 'phone', 'walk_in', 'staff_entered', name='appointmentsource'), nullable=False),
    sa.Column('special_note', sa.Text(), nullable=True),
    sa.Column('waiver_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('cancellation_policy_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('new', 'reviewed', 'converted', 'declined', name='appointmentrequeststatus'), nullable=False),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converted_to_appointment_id'], ['appointments.id'], name='fk_request_converted_to_appointment', use_alter=True),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_requests_tenant_id'), 'appointment_requests', ['tenant_id'], unique=False)
    op.create_table('providers',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('milano_code', sa.String(length=50), nullable=True),
    sa.Column('provider_type', sa.Enum('stylist', 'colourist', 'dualist', name='providertype'), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('home_phone', sa.String(length=30), nullable=True),
    sa.Column('cell_phone', sa.String(length=30), nullable=True),
    sa.Column('other_phone', sa.String(length=30), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('provider_photo_url', sa.String(length=500), nullable=True),
    sa.Column('sin_encrypted', sa.String(length=500), nullable=True),
    sa.Column('pay_type', sa.Enum('hourly', 'salary', name='paytype'), nullable=True),
    sa.Column('pay_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('can_be_cashier', sa.Boolean(), nullable=False),
    sa.Column('makes_appointments', sa.Boolean(), nullable=False),
    sa.Column('has_appointments', sa.Boolean(), nullable=False),
    sa.Column('booking_order', sa.Integer(), nullable=False),
    sa.Column('online_booking_visibility', sa.Enum('not_available', 'available_to_my_clients', 'available_to_all', name='onlinebookingvisibility'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_department_id'), 'providers', ['department_id'], unique=False)
    op.create_index(op.f('ix_providers_tenant_id'), 'providers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_providers_user_id'), 'providers', ['user_id'], unique=False)
    op.create_table('services',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('service_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('haircut_type', sa.Enum('type_1', 'type_2', 'type_2_plus', name='haircuttype'), nullable=True),
    sa.Column('pricing_type', sa.Enum('fixed', 'hourly', name='pricingtype'), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('processing_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('processing_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_addon', sa.Boolean(), nullable=False),
    sa.Column('requires_prior_consultation', sa.Boolean(), nullable=False),
    sa.Column('is_gst_exempt', sa.Boolean(), nullable=False),
    sa.Column('is_pst_exempt', sa.Boolean(), nullable=False),
    sa.Column('is_points_exempt', sa.Boolean(), nullable=False),
    sa.Column('split_commission', sa.Boolean(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_index(op.f('ix_services_tenant_id'), 'services', ['tenant_id'], unique=False)
    op.create_table('clients',
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('preferred_provider_id', sa.UUID(), nullable=True),
    sa.Column('referred_by_client_id', sa.UUID(), nullable=True),
    sa.Column('client_code', sa.String(length=20), nullable=False),
    sa.Column('milano_code', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('pronouns', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('home_phone', sa.String(length=30), nullable=True),
    sa.Column('work_phone', sa.String(length=30), nullable=True),
    sa.Column('cell_phone', sa.String(length=30), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('referral_source', sa.Enum('client_referral', 'google', 'instagram', 'walk_by', 'other', name='referralsource'), nullable=True),
    sa.Column('no_show_count', sa.Integer(), nullable=False),
    sa.Column('late_cancellation_count', sa.Integer(), nullable=False),
    sa.Column('account_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('waiver_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_policy_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['client_households.id'], ),
    sa.ForeignKeyConstraint(['preferred_provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['referred_by_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_household_id'), 'clients', ['household_id'], unique=False)
    op.create_index(op.f('ix_clients_tenant_id'), 'clients', ['tenant_id'], unique=False)
    op.create_table('provider_schedule_exceptions',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_schedule_exceptions_provider_id'), 'provider_schedule_exceptions', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_schedule_exceptions_tenant_id'), 'provider_schedule_exceptions', ['tenant_id'], unique=False)
    op.create_table('provider_schedules',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_schedules_provider_id'), 'provider_schedules', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_schedules_tenant_id'), 'provider_schedules', ['tenant_id'], unique=False)
    op.create_table('provider_service_prices',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_is_percentage', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_service_prices_provider_id'), 'provider_service_prices', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_service_prices_service_id'), 'provider_service_prices', ['service_id'], unique=False)
    op.create_index(op.f('ix_provider_service_prices_tenant_id'), 'provider_service_prices', ['tenant_id'], unique=False)
    op.create_table('stations',
    sa.Column('default_provider_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('station_type', sa.Enum('styling', 'colour_application', 'multi_purpose', name='stationtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_default_provider_id'), 'stations', ['default_provider_id'], unique=False)
    op.create_index(op.f('ix_stations_tenant_id'), 'stations', ['tenant_id'], unique=False)
    op.create_table('appointments',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('online_form', 'email', 'phone', 'walk_in', 'staff_entered', name='appointmentsource'), nullable=False),
    sa.Column('status', sa.Enum('requested', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show', name='appointmentstatus'), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_charge_pct', sa.Integer(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_group_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['appointment_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    op.create_table('appointment_items',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('second_provider_id', sa.UUID(), nullable=True),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('duration_override_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_is_locked', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='appointmentitemstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['second_provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_items_appointment_id'), 'appointment_items', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_items_provider_id'), 'appointment_items', ['provider_id'], unique=False)
    op.create_index(op.f('ix_appointment_items_start_time'), 'appointment_items', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointment_items_tenant_id'), 'appointment_items', ['tenant_id'], unique=False)
    op.create_table('appointment_reminders',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', name='reminderchannel'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'sent', 'failed', 'cancelled', name='reminderstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_reminders_appointment_id'), 'appointment_reminders', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_tenant_id'), 'appointment_reminders', ['tenant_id'], unique=False)
    op.create_table('appointment_request_items',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('converted_to_item_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('preferred_provider_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converted_to_item_id'], ['appointment_items.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['appointment_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_request_items_request_id'), 'appointment_request_items', ['request_id'], unique=False)
    op.create_index(op.f('ix_appointment_request_items_tenant_id'), 'appointment_request_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_request_items_tenant_id'), table_name='appointment_request_items')
    op.drop_index(op.f('ix_appointment_request_items_request_id'), table_name='appointment_request_items')
    op.drop_table('appointment_request_items')
    op.drop_index(op.f('ix_appointment_reminders_tenant_id'), table_name='appointment_reminders')
    op.drop_index(op.f('ix_appointment_reminders_appointment_id'), table_name='appointment_reminders')
    op.drop_table('appointment_reminders')
    op.drop_index(op.f('ix_appointment_items_tenant_id'), table_name='appointment_items')
    op.drop_index(op.f('ix_appointment_items_start_time'), table_name='appointment_items')
    op.drop_index(op.f('ix_appointment_items_provider_id'), table_name='appointment_items')
    op.drop_index(op.f('ix_appointment_items_appointment_id'), table_name='appointment_items')
    op.drop_table('appointment_items')
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_stations_tenant_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_default_provider_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_provider_service_prices_tenant_id'), table_name='provider_service_prices')
    op.drop_index(op.f('ix_provider_service_prices_service_id'), table_name='provider_service_prices')
    op.drop_index(op.f('ix_provider_service_prices_provider_id'), table_name='provider_service_prices')
    op.drop_table('provider_service_prices')
    op.drop_index(op.f('ix_provider_schedules_tenant_id'), table_name='provider_schedules')
    op.drop_index(op.f('ix_provider_schedules_provider_id'), table_name='provider_schedules')
    op.drop_table('provider_schedules')
    op.drop_index(op.f('ix_provider_schedule_exceptions_tenant_id'), table_name='provider_schedule_exceptions')
    op.drop_index(op.f('ix_provider_schedule_exceptions_provider_id'), table_name='provider_schedule_exceptions')
    op.drop_table('provider_schedule_exceptions')
    op.drop_index(op.f('ix_clients_tenant_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_household_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_services_tenant_id'), table_name='services')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_providers_user_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_tenant_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_department_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_appointment_requests_tenant_id'), table_name='appointment_requests')
    op.drop_table('appointment_requests')
    op.drop_index(op.f('ix_tenant_operating_hours_tenant_id'), table_name='tenant_operating_hours')
    op.drop_table('tenant_operating_hours')
    op.drop_index(op.f('ix_service_categories_tenant_id'), table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_client_households_tenant_id'), table_name='client_households')
    op.drop_table('client_households')
    # ### end Alembic commands ###
